export const ALL_PERMISSIONS = ['CREATE_ORDER','VIEW_ORDER','UPDATE_ORDER','MANAGE_KITCHEN_STATUS','CANCEL_ORDER','VOID_ORDER_ITEM','VIEW_TABLES','MANAGE_TABLES','VIEW_MENU','MANAGE_MENU','TAKE_PAYMENT','COMPLETE_PAYMENT','PRINT_RECEIPT','PROCESS_REFUND','VIEW_EMPLOYEES','MANAGE_EMPLOYEES','VIEW_REVENUE','VIEW_REPORTS','MANAGE_RESTAURANT','MANAGE_SETTINGS'];
export const DEFAULT_PERMISSIONS = {
  MANAGER: ALL_PERMISSIONS.filter((p) => !['MANAGE_RESTAURANT','MANAGE_SETTINGS'].includes(p)),
  CASHIER: ['CREATE_ORDER','VIEW_ORDER','UPDATE_ORDER','VIEW_TABLES','VIEW_MENU','TAKE_PAYMENT','COMPLETE_PAYMENT','PRINT_RECEIPT'],
  WAITER: ['CREATE_ORDER','VIEW_ORDER','UPDATE_ORDER','VIEW_TABLES','VIEW_MENU'],
  KITCHEN: ['VIEW_ORDER','MANAGE_KITCHEN_STATUS','VIEW_MENU'],
};
